language: node_js
node_js: 
  - ltd/*

script:
    - npm install
    - npm test
    - npm run build

deploy:
  provider: surge 
  skip_cleanup: true
  domain: swift-adjustment.surge.sh
  project: ./build/

on: 
  branch: master