language: node_js
node_js: 
  - lts/*

script:
    - nvm install ls-remote --lts
    - npm test
    - npm run build

deploy:
  provider: surge 
  skip_cleanup: true
  domain: swift-adjustment.surge.sh
  project: ./build/

on: 
  branch: master